module.exports = [
    "Orsang Camp",
    "Pawna Lake Camping by Weekend Feels",
    "Camp Roxx- Adventure Camp",
    "Devghatt Eco Tourism Camp Site",
    "Natural campsite",
    "Anan campground ",
    "Rayma campground",
    "Mahal campsite",
    "Sagai eco campsite",
    "Vadhvana wetland eco campsite",
    "Inatureclub forest campsite",
    "Safari camp osian",
    "Prince Desert camp",
    "Gandikota stay camping ",
    "Jungle camp",
    "Camp mustang ",
    "Bluerock campsite",
    "Hidden hills farm",
    "Pimpalgaon Joja Camping site",
    "Nagarbeda Camping",
    "Camp Himalayan Spirit Kasol",
    "Camp Carnival Kanatal",
    "The Regal Camp",
    "Tarsar Lake Camping Site ",
    "Camp Nampi",
    "BRO Camp",
    "Kasturikana Eco Camp",
    "Exoticamp's Nature Camp",
    "Encamp Adventures",
    "Dholkal Jungle Camp",
    "Dudhsagar Waterfall Camp Site",
    "Sal Wood Camp Base",
    "Nature Adventure Camp",
    "Black Eagles Camp",
    "Sohbar Adventure Camping ground",
    "Camp David",
    "Camp Baliman Campsite Gangtok",
    "Outlife Outbound Training Campsite",
    "Naru Camping site ",
    "Rocksport, Lucknow",
    "Nakaijuri Forest Camp",
]